version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
      timezone: America/New_York
    commit-message:
      prefix: "patch"
      prefix-development: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    reviewers:
      - davidlday
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      timezone: America/New_York
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    reviewers:
      - davidlday
