name: Test Upload Python Package

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  python-test-publish:
    uses: prosegrinder/.github/.github/workflows/python-test-publish.yaml@main
    secrets: inherit
