name: Upload Python Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  python-publish:
    uses: prosegrinder/.github/.github/workflows/python-publish.yaml@main
    secrets: inherit
