name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: prosegrinder/.github/.github/workflows/python-lint.yaml@main

  check-build:
    uses: prosegrinder/.github/.github/workflows/python-check-build.yaml@main
    needs: lint

  test:
    uses: prosegrinder/.github/.github/workflows/python-test.yaml@main
    needs: check-build
